import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./SharedComponent/Navbar";
import Footer from "./SharedComponent/Footer";
import ScrollRevealProvider from "./ScrollRevealProvider";
import { UserProvider } from "./context/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <ScrollRevealProvider>

          <UserProvider>
            <Navbar />
            <div className="min-h-[calc(100vh-480px)]">
             {children}
            </div>
            
            <Footer />
          </UserProvider>
          
        </ScrollRevealProvider>

      </body>
    </html>
  );
}